export enum GlobalPermissionScope {
  READ_USER_SKILLS = 'READ_USER_SKILLS',
  READ_USER_PROFILE = 'READ_USER_PROFILE',
  FIND_AS_COACH = 'FIND_AS_COACH',
  ALLOW_SALES_TO_USE_PERSONALIZED_PROFILE = 'ALLOW_SALES_TO_USE_PERSONALIZED_PROFILE'
}
